=== sonicdex/bitfinity-token-list/scripts/validators/tokenlist.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/sonicdex/bitfinity-token-list/main/src/tokenlist.schema.json",
  "title": "Sonic-Bitfinity Token List",
  "description": "Schema for lists of tokens compatible with the Sonic App",
  "definitions": {
    "Version": {
      "type": "object",
      "description": "The version of the list, used in change detection",
      "examples": [
        {
          "major": 1,
          "minor": 0,
          "patch": 0
        }
      ],
      "additionalProperties": false,
      "properties": {
        "major": {
          "type": "integer",
          "description": "The major version of the list. Must be incremented when tokens are removed from the list or token addresses are changed.",
          "minimum": 0,
          "examples": [1, 2]
        },
        "minor": {
          "type": "integer",
          "description": "The minor version of the list. Must be incremented when tokens are added to the list.",
          "minimum": 0,
          "examples": [0, 1]
        },
        "patch": {
          "type": "integer",
          "description": "The patch version of the list. Must be incremented for any changes to the list.",
          "minimum": 0,
          "examples": [0, 1]
        }
      },
      "required": ["major", "minor", "patch"]
    },
    "TokenInfo": {
      "type": "object",
      "description": "Metadata for a single token in a token list",
      "additionalProperties": false,
      "properties": {
        "address": {
          "type": "string",
          "description": "The checksummed address of the token on the bitfinity",
          "pattern": "^0x[a-fA-F0-9]{40}$",
          "examples": ["0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"]
        },
        "decimals": {
          "type": "integer",
          "description": "The number of decimals for the token balance",
          "minimum": 0,
          "maximum": 255,
          "examples": [18]
        },
        "name": {
          "type": "string",
          "description": "The name of the token",
          "minLength": 0,
          "maxLength": 60,
          "anyOf": [
            {
              "const": ""
            },
            {
              "pattern": "^[ \\S+]+$"
            }
          ],
          "examples": ["Sonic"]
        },
        "symbol": {
          "type": "string",
          "description": "The symbol for the token",
          "minLength": 0,
          "maxLength": 20,
          "anyOf": [
            {
              "const": ""
            },
            {
              "pattern": "^\\S+$"
            }
          ],
          "examples": ["SONIC"]
        },
        "logoURI": {
          "type": "string",
          "description": "A URI to the token logo asset; if not set, interface will attempt to find a logo based on the token address; suggest SVG or PNG of size 64x64",
          "format": "uri",
          "examples": ["ipfs://QmXfzKRvjZz3u5JRgC4v5mGVbm9ahrUiB4DgzHBsnWbTMM"]
        }
      },
      "required": ["address", "decimals", "name", "symbol"]
    }
  },
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the token list",
      "minLength": 1,
      "maxLength": 30,
      "pattern": "^[\\w ]+$",
      "examples": ["My Token List"]
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "description": "The timestamp of this list version; i.e. when this immutable version of the list was created"
    },
    "version": {
      "$ref": "#/definitions/Version"
    },
    "tokens": {
      "type": "array",
      "description": "The list of tokens included in the list",
      "items": {
        "$ref": "#/definitions/TokenInfo"
      },
      "minItems": 1,
      "maxItems": 10000
    }
  },
  "required": ["name", "timestamp", "version", "tokens"]
}

=== sonicdex/bitfinity-token-list/src/token-list.json
{
  "name": "Sonic Bitfinity token list",
  "timestamp": "2024-12-24T13:34:29.261Z",
  "version": {
    "major": 1,
    "minor": 1,
    "patch": 0
  },
  "tokens": [
    {
      "address": "0x491016bf872d35a798c601d53442775c621bf91b",
      "decimals": 8,
      "name": "Sonic2",
      "symbol": "SONIC2",
      "logoURI": "https://cdn.sonic.ooo/v3/token_images/0x491016bf872d35a798c601d53442775c621bf91a.webp"
    },
    {
      "address": "0x51ccde9ca75d95bb55ece1775fcbff91324b18a6",
      "decimals": 8,
      "name": "Internet Computer",
      "symbol": "ICP",
      "logoURI": "https://cdn.sonic.ooo/v3/token_images/0x51ccde9ca75d95bb55ece1775fcbff91324b18a6.webp"
    },
    {
      "address": "0x491016bf872d35a798c601d53442775c621bf91a",
      "decimals": 8,
      "name": "Sonic",
      "symbol": "SONIC",
      "logoURI": "https://cdn.sonic.ooo/v3/token_images/0x491016bf872d35a798c601d53442775c621bf91a.webp"
    },
    {
      "address": "0x491016bf872d35a798c601d53442775c621bf91e",
      "decimals": 8,
      "name": "Sonic1",
      "symbol": "SONIC1",
      "logoURI": "https://cdn.sonic.ooo/v3/token_images/0x491016bf872d35a798c601d53442775c621bf91a.webp"
    }
  ]
}
